import { ActionType } from '../../../models/ActionsModal';

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const EDIT_NEW_PROJECT = 'EDIT_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SPINNER_IN_PROJECT = 'SPINNER_IN_PROJECT';
export const ERROR_IN_PROJECT = 'ERROR_IN_PROJECT';
export const ON_PROJECT_SELECTED = 'ON_PROJECT_SELECTED';
export const ON_PROJECT_SELECTED_FOR_TRACKING = 'ON_PROJECT_SELECTED_FOR_TRACKING';
export const ON_PROJECT_ACTIONS_MODAL_TOGGLE = 'ON_PROJECT_ACTIONS_MODAL_TOGGLE';
export const ON_PROJECT_DELETE_CONFIRM_MODAL_TOGGLE = 'ON_PROJECT_DELETE_CONFIRM_MODAL_TOGGLE';
export const ON_DELETE_SUCCESS = 'ON_DELETE_SUCCESS';
export const ON_DELETE_ERROR = 'ON_DELETE_ERROR';
export const ON_DELETE_SPINNER = 'ON_DELETE_SPINNER';
export const REFRESH_PROJECTS_AFTER_DELETE = 'REFRESH_PROJECTS_AFTER_DELETE';
export const ON_REFRESH_PROJECTS_AFTER_MODIFY = 'ON_REFRESH_PROJECTS_AFTER_MODIFY';
export const MODIFIED_PROJECT_SPINNER = 'MODIFIED_PROJECT_SPINNER';
export const MODIFIED_PROJECT_ERROR = 'MODIFIED_PROJECT_ERROR';
export const MODIFY_PROJECT_SUCCESS_TOGGLE = 'MODIFY_PROJECT_SUCCESS_TOGGLE';

export type ProjectsActionTypes = ActionType;
