import { ActionType } from '../../../models/ActionsModal';

export const GET_ALL_STORIES = 'GET_ALL_STORIES';
export const ADD_NEW_STORY = 'ADD_NEW_STORY';
export const SPINNER_IN_STORY = 'SPINNER_IN_STORY';
export const ERROR_IN_STORY = 'ERROR_IN_STORY';
export const ON_STORY_SELECTED = 'ON_STORY_SELECTED';
export const ON_STORY_DELETE_CONFIRM_MODAL_TOGGLE = 'ON_STORY_DELETE_CONFIRM_MODAL_TOGGLE';
export const ON_DELETE_SUCCESS = 'ON_DELETE_SUCCESS';
export const ON_DELETE_ERROR = 'ON_DELETE_ERROR';
export const ON_DELETE_SPINNER = 'ON_DELETE_SPINNER';
export const REFRESH_STORYS_AFTER_DELETE = 'REFRESH_STORYS_AFTER_DELETE';
export const ON_REFRESH_STORYS_AFTER_MODIFY = 'ON_REFRESH_STORYS_AFTER_MODIFY';
export const MODIFIED_STORY_SPINNER = 'MODIFIED_STORY_SPINNER';
export const MODIFIED_STORY_ERROR = 'MODIFIED_STORY_ERROR';
export const MODIFY_STORY_SUCCESS_TOGGLE = 'MODIFY_STORY_SUCCESS_TOGGLE';

export type StoriesActionTypes = ActionType;
